myproject03/myproject03/urls.py
from django.contrib import admin
from django.urls import path
from myapp03 import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.index),
    path('base/', views.index),
    path('write_form/', views.write_form),
    path('insert/', views.insert),
    path('list/', views.list),
    path('delete/<int:board_idx>/', views.delete),
    path('delete/<int:writer_idx>/', views.delete),
    path('update/<int:board_idx>/', views.update),
    path('update_now/', views.update_now),
    path('detail/<int:board_idx>/', views.detail),
    path('download_count', views.download_count),
    path('download/', views.download),
    path('comment_insert/', views.comment_insert),
    path('signup/', views.signup),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('melon/', views.melon),
    path('weather/', views.weather),
    path('map/', views.map),
    path('wordcloud/', views.wordcloud),
    path('attendance/', views.attendance),
]

myproject03/myapp03/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Board(models.Model):
    idx = models.AutoField(primary_key = True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(null=False, max_length=200)
    content = models.TextField(null=False)
    hit = models.IntegerField(default=0)
    post_date = models.DateField(default=datetime.now,blank = True)
    filename = models.CharField(null=False, max_length =500, blank= True, default='')
    filesize=models.IntegerField(default=0)
    down=models.IntegerField(default=0)

    def hit_up(self):
        self.hit += 1

    def down_up(self):
        self.down += 1

class Comments(models.Model):
    board = models.ForeignKey(Board,on_delete=models.CASCADE)
    writer = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.TextField(null=False)
    post_date = models.DateField(default=datetime.now,blank = True)

class Forecast(models.Model):
    city = models.CharField(null=False, max_length=50)
    tmef = models.TextField(null=True)
    wf = models.TextField(null=True)
    tmn = models.IntegerField(default = 0)
    tmx = models.IntegerField(default = 0)
    

myproject03/myapp03/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.forms import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')

    class Meta:
        model = User
        fields = ("username","email")

myproject03/myapp03/views.py
import csv
from myapp03.models import Forecast
from .forms import UserForm
from django.contrib.auth import authenticate, login

from django.views.decorators.csrf import csrf_exempt
from myapp03.models import Board, Comments
import urllib.parse
import math
from django.db.models import Q
from django.shortcuts import HttpResponse, render, redirect, get_object_or_404
from django.http.response import JsonResponse

from myapp03 import bigdataProcess
from django.db.models.aggregates import Count
import pandas as pd
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
import json


import requests
from bs4 import BeautifulSoup

# Create your views here.
UPLOAD_DIR = 'C:\\djangostudy\\upload\\'


def melon(request):
    datas = []
    bigdataProcess.melon_crawing(datas)
    return render(request, 'bigdata/melon.html', {'datas': datas})


def weather(request):
    last_date = Forecast.objects.values('tmef').order_by('-tmef')[:1]
    print('last_date :', len(last_date))
    weather = {}
    bigdataProcess.weather_crawing(last_date, weather)

    print('last_date query :', str(last_date.query))

    # for i in weather:
    #     for j in weather[i]:
    #         dto = Forecast(city=i, tmef=j[0], wf=j[1], tmn=j[2], tmx=j[3])
    #         dto.save()

    weather_data = Forecast.objects.all()
    result = Forecast.objects.filter(city='부산')
    result1 = Forecast.objects.filter(city='부산').values(
        'wf').annotate(dcount=Count('wf')).values("dcount", "wf")
    print('result1 query :', str(result1.query))

    df = pd.DataFrame(result1)

    image_dic = bigdataProcess.weather_make_chart(result1, df.wf, df.dcount)
    return render(request, 'bigdata/weather_chart.html', {"img_data": image_dic, "weather_data": weather_data})


def map(request):
    bigdataProcess.map()
    return render(request, "bigdata/map.html")


def wordcloud(request):
    w_path = 'C:\\djangostudy\\myProject03\\data\\'
    data = json.loads(open(w_path+'4차 산업혁명.json',
                      'r', encoding='utf-8').read())
    # print(data)
    bigdataProcess.make_wordCloud(data)
    return render(request, "bigdata/wordchart.html", {"img_data": "k_wordCloud.png"})


def attendance(request):

    req = requests.get(
        'https://www.koreabaseball.com/History/Crowd/GraphDaily.aspx')
    soup = BeautifulSoup(req.text, 'html.parser')
    # print(soup)

    bigdataProcess.attendance(soup)
    return render(request, "bigdata/attendance.html", {"img_data": "KBO_attendance.png"})

################# 게시판 ########################


def index(request):
    return render(request, 'base.html')


@ login_required(login_url='/login/')
def write_form(request):
    return render(request, 'board/insert.html')


@ csrf_exempt
def insert(request):
    fname = ''
    fsize = 0
    if 'file' in request.FILES:
        file = request.FILES['file']
        fname = file.name
        fsize = file.size
        fp = open('%s%s' % (UPLOAD_DIR, fname), 'wb')
        for chunk in file.chunks():
            fp.write(chunk)
        fp.close()

    dto = Board(writer=request.user,
                title=request.POST['title'],
                content=request.POST['content'],
                filename=fname,
                filesize=fsize
                )
    dto.save()
    return redirect('/base')


def list(request):
    page = request.GET.get('page', '1')
    word = request.GET.get('word', '')
    field = request.GET.get('field', 'title')

    if field == 'all':
        boardCount = Board.objects.filter(Q(writer__contains=word) | Q(
            title__contains=word) | Q(content__contains=word)).count()
    elif field == 'writer':
        boardCount = Board.objects.filter(Q(writer__contains=word)).count()
    elif field == 'title':
        boardCount = Board.objects.filter(Q(title__contains=word)).count()
    elif field == 'content':
        boardCount = Board.objects.filter(Q(content__contains=word)).count()
    else:
        boardCount = Board.objects.all().count()

    pageSize = 5  # 한 화면에 게시글 수
    blockPage = 3  # 보이는 페이지 수
    currentPage = int(page)
    # 게시글 수 32 : pagesize:5
    start = (currentPage-1)*pageSize
    totPage = math.ceil(boardCount/pageSize)  # 게시글의 전체 페이지 수
    startPage = math.floor((currentPage - 1)/blockPage)*blockPage + 1
    endPage = startPage + blockPage - 1

    rowNo = boardCount-(int(page)-1)*pageSize
    if endPage > totPage:
        endPage = totPage  # endPage = 7

    if field == 'all':
        boardList = Board.objects.filter(Q(writer__contains=word) | Q(title__contains=word) | Q(
            content__contains=word)).order_by('-idx')[start:start+pageSize]
    elif field == 'writer':
        boardList = Board.objects.filter(
            Q(writer__contains=word)).order_by('-idx')[start:start+pageSize]
    elif field == 'title':
        boardList = Board.objects.filter(
            Q(title__contains=word)).order_by('-idx')[start:start+pageSize]
    elif field == 'content':
        boardList = Board.objects.filter(
            Q(content__contains=word)).order_by('-idx')[start:start+pageSize]
    else:
        boardList = Board.objects.all().order_by('-idx')[start:start+pageSize]

    context = {'boardList': boardList,
               'startPage': startPage,
               'blockPage': blockPage,
               'endPage': endPage,
               'totPage': totPage,
               'boardCount': boardCount,
               'currentPage': currentPage,
               'field': field,
               'word': word,
               'rowNo': rowNo,
               'range': range(startPage, endPage+1)}
    return render(request, 'board/list.html', context)


def download_count(request):
    id = request.GET['idx']
    dto = Board.objects.get(idx=id)
    dto.down_up()
    dto.save()
    count = dto.down
    return JsonResponse({'idx': id, 'count': count})


# 다운로드
def download(request):
    id = request.GET['idx']
    dto = Board.objects.get(idx=id)
    path = UPLOAD_DIR+dto.filename
    filename = urllib.parse.quote(dto.filename)

    with open(path, 'rb') as file:
        response = HttpResponse(file.read(),
                                content_type='application/octet-stream')
        response['Content-Disposition'] = 'attachment;filename*=UTF-8''{0}'.format(
            filename)
    return response


def detail(request, board_idx):
    dto = Board.objects.get(idx=board_idx)
    dto.hit_up()
    dto.save()

    # commentList= Comments.objects.filter(board_idx=board_idx).order_by('-idx')

    return render(request, 'board/detail.html', {'dto': dto})


def update(request, board_idx):
    dto = Board.objects.get(idx=board_idx)
    return render(request, 'board/update.html', {'dto': dto})


# 수정
@csrf_exempt
def update_now(request):
    id = request.POST['idx']
    dto = Board.objects.get(idx=id)
    fname = dto.filename
    fsize = dto.filesize

    if 'file' in request.FILES:
        file = request.FILES['file']
        fname = file.name
        fsize = file.size
        fp = open('%s%s' % (UPLOAD_DIR, fname), 'wb')
        for chunk in file.chunks():
            fp.write(chunk)
        fp.close()

    update_dto = Board(
        id,
        writer=request.user,
        title=request.POST['title'],
        content=request.POST['content'],
        filename=fname,
        filesize=fsize
    )
    update_dto.save()
    return redirect('/list')


def delete(request, board_idx):
    dto = Board.objects.get(idx=board_idx)
    dto.delete()
    return redirect('/list')


def delete(request, writer_idx):
    dto = Comments.objects.get(idx=writer_idx)
    dto.delete()
    return redirect('/list')


@csrf_exempt
@login_required(login_url='/login/')
def comment_insert(request):
    id = request.POST['idx']
    board = get_object_or_404(Board, pk=id)
    dto = Comments(
        board=board,
        writer=request.user,
        content=request.POST['Comment']
    )
    dto.save()
    return redirect('/detail/'+id)


def signup(request):
    if request.method == "POST":  # 회원가입 insert
        form = UserForm(request.POST)
        if form.is_valid():
            print('signup POST valid')
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)

            login(request, user)
            return redirect('/')
        else:
            print('signup POST un_valid')

    else:  # 회원가입 폼으로
        form = UserForm()

    return render(request, 'common/signup.html', {'form': form})

myproject03/myapp03/templates/board/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <table class="table">
        <tr class="table-warning">
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>작성일</th>
            <th>조회수</th>
            <th>첨부파일</th>
            <th>파일이미지</th>
        </tr>
        <tbody>
            <tr>
              <td>{{dto.idx}}</td>
              <td>{{dto.title}}</td>
              <td>{{dto.writer.username}}</td>
              <td>{{dto.post_date}}</td>
              <td>{{dto.hit}}</td>
              <td>{{dto.filename}}</td>
              <td>{% if dto.filesize > 0 %}
                <span class="_imgs" data-url="/download_count?idx={{dto.idx}}">
                  <img src="{% static 'images/file.jpg' %}"></td>
                </span>
                {% endif %}  
            <td class="_downCnt">{{board.down}}</td>
            </tr>
          </tbody>
    </table>
    {% if dto.writer.username == user.username %}
      <button type="button" class="btn btn-warning _update" data-uri="/update/{{dto.idx}}">수정</button>
      
      <button type="button" class="btn btn-light _delete" data-uri="/delete/{{dto.idx}}">삭제</button>

      <br/><br/>
      {% endif %}
    <h4>Comment</h4>
    <form
     action="/comment_insert/" method="post">
      <input type="hidden" name="idx" value="{{dto.idx}}">
      <div class="form-group">  
          <textarea class="form-control" name="Comment" rows="5" placeholder="Comment Insert"></textarea>
      </div>
        <button type="submit" class="btn btn-warning">CommentWrite</button>
    </form>
    <!-- comment count -->
    <div class="mt-3">Comment({{dto.comments_set.count}})</div>
   
    <div>
    {% if dto.comments_set.count > 0 %}
    <div class="container">
      <table class="table">
          <tr class="table">
              <th>제목</th>
              <th>작성자</th>
              <th>작성일</th>
              <th></th>
            </tr>
      <!-- comment list -->
      {% for comment in dto.comments_set.all %}
      <tbody>
        <tr>
            <td>{{comment.content}}</td>
            <td>{{comment.writer}}</td>
            <td>{{comment.post_date}}</td>
            {% if comment.writer.username == user.username %}
            <td><button type="button" class="btn btn-warning _update" data-uri="/update/{{dto.comments.idx}}">수정</button>
            <button type="button" class="btn btn-light _delete" data-uri="/delete/{{dto.comments.idx}}">삭제</button></td>
          {% endif %}
      <br/><br/>
        </tr>
      {% endfor %}
      </tbody>
    </div>
    {% endif %}
    </div>
</div>

{% endblock %}

{% block script %}
<script>
  $("._update").on('click',function(){
    location.href=$(this).data('uri')
  })


  $("._delete").on('click',function(){
    alert('정말 삭제할까요?')
    location.href=$(this).data('uri')
  })
</script>

{% endblock %}

myproject03/myapp03/templates/board/insert.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h2>Insert</h2>
    <form action="/insert/" method="post" enctype="multipart/form-data">
      <div class="form-group">
        <label for="writer">writer</label>
        <input type="text" class="form-control" id="writer" placeholder="Enter writer" name="writer" value="{{user.username}}">
      </div>
      <div class="form-group">
        <label for="text">title</label>
        <input type="text" class="form-control" id="title" placeholder="Enter title" name="title">
      </div>
      <div class="form-group">
        <label for="text">content</label>
        <textarea class="form-control" rows="5" id="content" placeholder="Enter content" name="content"></textarea>
      </div>
      <div class="form-group">
        <label for="text">file</label>
        <input type="file" class="form-control" id="file" placeholder="Enter file" name="file"><br/>
      <button type="submit" class="btn btn-primary">글쓰기</button>
    </form>
  </div>
  
{% endblock %}

myproject03/myapp03/templates/board/list.html
{% extends 'base.html' %}
{% load static %}
{% load board_filter %}
{% block content %}
<div class="container">
  <div class="d-flex justify-content-end">
    <form action="/list" method="GET" class="form-inline mr-3">
        <select class="form-control mr-sm-1" id="field" name="field">
          <option value="title">제목</option>
          <option value="writer">작성자</option>
          <option value="content">내용</option>
          <option value="all">이름+제목+내용</option>
            <script>
              //$('#field').val('{{field}}').prop("selected",true);
              document.getElementById('field').value="{{field}}"
            </script>
        </select>
        <input type="text" class="form-control" id="word" placeholder="Enter Search" name="word" value="{{word}}">
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
<h1>BOARD({{boardCount}})</h1>
    <table class="table">
      <tr class="table-warning">
                <th>번호</th>
                <th>제목</th>
                <th>작성자</th>
                <th>작성일</th>
                <th>조회수</th>
                <th>첨부파일</th>
                <th>파일이미지</th>
                <th>다운로드</th>
          </tr>
      </thead>
      <tbody>
        {% for board in boardList %}
        <tr>
          <td>{{rowNo|sub:forloop.counter0}}</td>
          <td><a href="/detail/{{board.idx}}">{{board.title}}</a></td>
          <td>{{board.writer}}</td>
          <td>{{board.post_date}}</td>
          <td>{{board.hit}}</td>
          <td>{{board.filename}}</td>
          <td>{% if board.filesize > 0 %}
              <span class="_imgs" data-url="/download_count?idx={{board.idx}}">
                <img src="{% static 'images/file.jpg' %}"></td>
              </span>
              {% endif %}  
          <td class="_downCnt">{{board.down}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <!-- 페이지 번호 -->
    <ul class="pagination">
      {% if startPage > blockPage %}
        <li class="page-item"><a class="page-link" href="?page={{startPage|add:-1}}&field={{field}}&word={{word}}">Previous</a></li>
      {% endif %}
      
      {% for i in range %}
        {% if i == currentPage %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}&field={{field}}&word={{word}}">{{i}}</a></li>
        {% endif %}
      {% endfor %}
      {% if endPage < totPage %}
        <li class="page-item"><a class="page-link" href="?page={{endPage|add:1}}&field={{field}}&word={{word}}">Next</a></li>
      {% endif %}
    </ul>
</div>

{% endblock %}

{% block script %}
  <script>
    $("._imgs") .on("click",function(){
      _imgs = $(this)
      $.ajax({
          type: "GET",
          url : $(this).attr('data-url'),
          success : function(data){ 
              //alert(data.count)
              _imgs.parent().parent().find("._downCnt").text(data.count) 
              location.href = "/download?idx=" + data.idx
          }                 
      })
    })
  </script>
{% endblock %}

myproject03/myapp03/templates/board/list_page.html
{% extends 'base.html' %}
{% load static %}
{% load board_filter %}
{% block content %}
<div class="container">
    <div class="d-flex justify-content-start mb-3">
        <form action="/list_page" method="get" class="form-inline mr-3">

            <input type="word" class="form-control mr-sm-1" id="word" placeholder="Enter Search" name="word"
                value="{{word}}">

            <button type="submit" class="btn btn-secondary">Search</button>
        </form>
    </div>
    <h2>BOARD_PAGE ({{boardCount}})</h2>

    <table class="table">
        <thead>
            <tr>
                <th>번호</th>
                <th>작성자</th>
                <th>제목</th>
                <th>작성일</th>
                <th>조회수</th>
                <th>첨부파일</th>
                <th>다운로드</th>
            </tr>
        </thead>
        <tbody>
            {% for board in page_list %}
            <tr>
                <td>{{rowNo|sub:forloop.counter0}}</td>
                <td>{{board.writer}}</td>
                <td><a href="/detail/{{board.id}}">{{board.title}}</a></td>
                <td>{{board.post_date | date:'Y-m-d'}}</td>
                <td>{{board.hit}}</td>
                <td>
                    {% if board.filesize > 0 %}
                    <span class="_imgs" data-url="/download_count?id={{board.id}}">
                        <img src="{% static 'images/file.jpg' %}">
                    </span>
                </td>

                {% endif %}
                <td class="downCnt">{{board.down}}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>

    <!-- 페이지번호 -->
    <ul class="pagination">
        {% if page_list.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{page_list.previous_page_number}}&word={{word}}">이전</a>
        </li>
        {% endif %}


        {% if page_list.has_next %} <li class="page-item"><a class="page-link"
                href="?page={{page_list.next_page_number}}&word={{word}}">다음</a></li>
        {% endif %}
    </ul>



</div>
{% endblock %}

{% block script %}
<script>
    $("._imgs").on("click", function () {
        _imgs = $(this)
        $.ajax({
            type: "GET",
            url: $(this).attr('data-url'),
            success: function (data) {
                _imgs.parent().parent().find(".downCnt").text(data.count)
                location.href = "/download?id=" + data.id
            }
        })
    })

</script>
{% endblock %}

myproject03/myapp03/templates/board/update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h2>Insert</h2>
    <form action="/update_now/" method="post" enctype="multipart/form-data">
      <div class="form-group">
        <input type="hidden" name="idx" value="{{dto.idx}}">
        <label for="writer">writer</label>
        <input type="text" class="form-control" id="writer" placeholder="Enter writer" name="writer" value="{{dto.writer}}">
      </div>
      <div class="form-group">
        <label for="text">title</label>
        <input type="text" class="form-control" id="title" placeholder="Enter title" name="title" value="{{dto.writer}}">
      </div>
      <div class="form-group">
        <label for="text">content</label>
        <textarea class="form-control" rows="5" id="content" placeholder="Enter content" name="content">{{dto.content}}</textarea>
      </div>
      <div class="form-group">
        <label for="text">file</label>
        <input type="file" class="form-control" id="file" placeholder="Enter file" name="file">{{dto.filename}}<br/>
      <button type="submit" class="btn btn-primary">글쓰기</button>
    </form>
  </div>
  
{% endblock %}

myproject03/myapp03/templates/board/write.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h3>Insert</h3>
    <form action="/insert/" method="post" enctype="multipart/form-data">
        <!-- {% csrf_token %} -->
        writer: <input type="text" name="writer"><br />
        title: <input type="text" name="title"><br />
        content: <textarea name="content" rows="5" cols="50"></textarea><br />
        file: <input type="file" name="file"><br />
        <input type="submit" value="글쓰기">
    </form>
</body>

</html>